### PR TITLE
allow input grid as dataset

### PR DESCRIPTION
**Pull request by cosunae**
Description
==========

currently the function combine_grid_information fails if the grid_file parameter is an xr.Dataset and not a filename. 
This PR applies fixes to support the argument as an xr.Dataset

### CODE REVIEW

**Comment by cosunae** [comment]
launch jenkins

**Review by victoria-cherkas — APPROVED** [review]

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Comment by cosunae** [comment]
launch jenkins

**Pull request merged**
